version: "3.8"
services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - 5000:8080
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - Redis=redis:6379
    depends_on:
      - redis
  redis:
    image: redis:latest
    ports:
      - 6379:6379
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    volumes:
      - ./realm:/opt/keycloak/data/import
    command: start-dev --import-realm
    environment:
      - KC_BOOTSTRAP_ADMIN_USERNAME=admin
      - KC_BOOTSTRAP_ADMIN_PASSWORD=admin
      - KC_OVERRIDE=true
      - KC_DIR=/opt/keycloak/data/import
    ports:
      - 8081:8080